### ISSUE TITLE
Utilize Maven repository for versioning

### ISSUE THREAD

**Issue by magneticflux-** [OpenFTC/OpenFTC-app#11]
I created and am maintaining a public Maven repository that hosts `.aar`s from the `ftc_app` repository. Currently, Pattonville Robotics (2866, 2867, 7856) use this repository to manage transitive dependencies with a our shared library "Common Code". Here is the repository: [link](https://github.com/Pattonville-Robotics/ftc-lib-repo).

Would you be interested in using this for your build scripts?

**Comment by ItsHarper** [comment]
I can't say I really see an advantage to setting things up that way. We can download the files from GitHub easily enough, and we're not dependent on a third party that way.

Thanks for the offer though! Your common code library looks very cool. Is it intended to be open source?

**Comment by magneticflux-** [comment]
@NoahAndrews Right now it doesn't have a stable public API, so we're cautious about releasing it. We should definitely license it eventually though. I'm thinking LGPLv3 or something similar.
