### ISSUE TITLE
Add a summary of OpenFTC for FTAs and Inspectors to the About Screen

### ISSUE THREAD

**Issue by ItsHarper** [OpenFTC/OpenFTC-app#19]

**Comment by WardBenjamin** [comment]
I would assign myself to this but I can't.

So fyi, I'm working on this. It's mostly done; should be pushed tomorrow if I have enough time.

**Comment by ItsHarper** [comment]
Great!

**Comment by Windwoes** [comment]
@WardBenjamin I would have a button which, when pressed, would popup the summary in an Alert Dialog.
