### ISSUE TITLE
Create vanilla repository 

### ISSUE THREAD

**Issue by ItsHarper** [OpenFTC/OpenFTC-app#23]
For people who want easy access to the complete source code but don't trust the community not to break things

**Comment by Windwoes** [comment]
But we already have the unmodified branch

**Comment by ItsHarper** [comment]
Yeah, just a more visible version of that. In addition to visibility, you remove the risk of accidentally merging or downloading the full version from master.

**Comment by ItsHarper** [comment]
I guess the ability to build a stock app from OpenFTC projects kind of makes this unnecessary.
