### ISSUE TITLE
Error: Robot failed to start: Attempt to invoke.... ConfigurationDevice.isDeviceFlavor() on a null object reference

### ISSUE THREAD

**Issue by WardBenjamin** [OpenFTC/OpenFTC-app#39]
Full error:
![jpeg_20171207_190943](https://user-images.githubusercontent.com/4739008/33746173-95652e38-db89-11e7-8d38-0b4f1dd704ea.jpg)

See RC log: https://gist.github.com/WardBenjamin/112e8b43ed487c52b4d96da8ac2471f7
See config: https://gist.github.com/WardBenjamin/77420d2f75d2cd2479ce642f69574535

**Comment by ItsHarper** [comment]
Also of note: the config screen shows no config files, and scans turn up empty.

**Comment by WardBenjamin** [comment]
RC log for commit hash e5003f776024a7bf0bd16ef80e0cba87c5309a22: https://gist.github.com/WardBenjamin/fe73751eeb12a5756a8366d791de2240

**Comment by ItsHarper** [comment]
Access to the `mapTagToUserType` object is not thread-safe. Worth noting.

**Comment by ItsHarper** [comment]
Might be a 3.5 issue, it only showed up after updating.

**Comment by ItsHarper** [comment]
I'm expecting to see a "Filtering UnspecifiedMotor class" message.

**Comment by ItsHarper** [comment]
What the log should look like (with latest logging additions): https://gist.github.com/NoahAndrews/dd331687e2b9b8a460b0d8b6a8ba23fb

**Comment by Windwoes** [comment]
@WardBenjamin Have you tried:

 - Build -- > Clean
 - Build --> Rebuild
 - File --> Invalidate Caches / Restart
 - Completely uninstalling the RC app before deploying from AS

(I sometimes have an issue where the RC says I have duplicate OpModes even though I don't and one of the above steps fixes it)

**Comment by ItsHarper** [comment]
@WardBenjamin As a reminder, please run my latest logging code before you try to fix the issue by any of those steps.

**Comment by WardBenjamin** [comment]
RC log for commit hash e3e6643408285a5c74779d28cfa9ba574fe7c3c8:
https://gist.github.com/WardBenjamin/68612d108e223573a7b3d9e4109093a6

**Comment by ItsHarper** [comment]
This turned out to be an Instant Run issue. Which I think I've actually fixed.
