### ISSUE TITLE
Consider forcing Cold Swaps for Instant Run

### ISSUE THREAD

**Issue by ItsHarper** [OpenFTC/OpenFTC-app#41]

**Comment by ItsHarper** [comment]
![image](https://user-images.githubusercontent.com/10224994/34183677-ec6874ec-e4e9-11e7-9242-16430fa18ed9.png)

**Comment by Windwoes** [comment]
I'd say don't force and just have a warning saying that hotswap changes won't persist on reload

**Comment by qwertychouskie** [comment]
Personally I think hot swaps are way more trouble than they are benefit.  In past years they have caused much confusion and pain on my team.
