### ISSUE TITLE
Update for SDK v4?

### ISSUE THREAD

**Issue by qwertychouskie** [OpenFTC/OpenFTC-app#79]
Any info on when this will be updated for version 4 of the SDK?

**Comment by ItsHarper** [comment]
When I get some time to work on it. Also, there was a large amount of change in 4.0. My update script will need some tweaking, and there will be at least a couple of painful merge conflicts to resolve. For example, we modified the About screen to add an About OpenRC button. The About screen implementation that we modified got completely replaced in 4.0. 

Hopefully it won't be too long, but I'm not guaranteeing a timeline right now.

**Comment by ItsHarper** [comment]
Note to self: Make sure that we replace the old version of Vuforia stored on the phone

**Comment by qwertychouskie** [comment]
Any updates on this?  Our robot is almost ready to code but I still haven't created our repo because I want to use OpenRC...

**Comment by Windwoes** [comment]
@qwertychouskie we're both busy so we haven't had time to work on it yet :(

**Comment by qwertychouskie** [comment]
So... Still no 4.x?

**Comment by rbrott** [comment]
It looks like there will never be 4.x support. According to @FROGbots-4634:
> v4.x is dead in the water, however, v5.x is on the roadmap.

**Comment by Windwoes** [comment]
@qwertychouskie [OpenRC-Turbo](https://github.com/OpenFTC/OpenRC-Turbo) has been refreshed and is now based off of SDK v5.0.
